MxlCalc/MxlCalc/Models/ErrorViewModel.cs
using System;

namespace MxlCalc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MxlCalc/MxlCalc/Controllers/BinaryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MxlCalc.Models;
using Services;


namespace MxlCalc.Controllers
{
    public class BinaryController : Controller
    {
     

        [HttpGet]
        public IActionResult Index()
        {
            
            return View();
        }
        [HttpGet]
        public IActionResult Operations()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Operations(string setA, string setB, string operation, string type)
        {
            OperationsService operationsServise = new OperationsService(setA, setB, operation, type);
            ViewBag.Result = operationsServise.ToString();
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MxlCalc/MxlCalc/Controllers/CombinationsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Models;
using Services;

namespace MxlCalc.Controllers
{
    public class CombinationsController : Controller
    {
        private CombinationService _combinationService;
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.formType = "form1.cshtml";
            return View();
        }
        [HttpPost]
        public IActionResult Index(string answer, string n, string m, string k)
        {
            
            if (n!=null && m == null)
            {
                _combinationService = new CombinationService(n,true);
                ViewBag.TypeOfConfigure = Combinations.TypeOfConfigure;
                ViewBag.Result = Combinations.Result;
            }
            else if (m != null && n == null)
            {
                _combinationService = new CombinationService(m,k,true);
                ViewBag.TypeOfConfigure = Combinations.TypeOfConfigure;
                ViewBag.Result = Combinations.Result;
            }
            else if (n != null && m != null)
            {
                _combinationService = new CombinationService(n,m);
                ViewBag.TypeOfConfigure = Combinations.TypeOfConfigure;
                ViewBag.Result = Combinations.Result;
            }
            else
            {
                _combinationService = new CombinationService(answer);
            }
            ViewBag.formType = _combinationService.Form;
            return View();
        }
      
    }
}

MxlCalc/MxlCalc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MxlCalc.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MxlCalc.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index(string themes)
        {
            if (themes == "sets")
            {
                return Redirect("/Set/Index");
            }
            else if (themes == "binary__relations")
            {
                return Redirect("/Binary/Index");
            }
            else if (themes == "combinations")
            {
                return Redirect("/Combinations/Index");
            }
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MxlCalc/MxlCalc/Controllers/SetController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Services;

namespace MxlCalc.Controllers
{
    public class SetController : Controller
    {
        [HttpGet]
        public IActionResult Index(string calculators)
        {
            if (calculators == "operations")
            {
                return Redirect("/Set/Operations");
            }
            else if (calculators == "equation")
            {
                return Redirect("/Set/Equation");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Operations(string setA, string setB, string operation, string type)
        {
            if (operation != null)
            {
                OperationsService operationsServise = new OperationsService(setA, setB, operation, type);
                ViewBag.Result = operationsServise.ToString();
            }
           
            return View();
        }
    }
}

MxlCalc/MxlCalc/Views/Binary/Characteristics.cshtml
@{
    ViewData["Title"] = "Бинарные отношения";
}
sdsdsd

MxlCalc/MxlCalc/Views/Combinations/Index.cshtml
@{
    ViewData["Title"] = "Комбинаторные конфигурации";
}
<link href="@Url.Content("~/css/operations.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/comb.min.css")" rel="stylesheet" type="text/css" />
<section class="main__calculator">
    <h2 class="main__calculator-title">
        Комбинаторные конфигурации
    </h2>
    <div class="main__calculator-body">
        <partial name="~/Views/Combinations/@ViewBag.formType" />
     </div>
</section>

MxlCalc/MxlCalc/Views/Combinations/form1.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top">
        <h4 class="form-top__text">Важен ли порядок элементов?</h4>
        <label class="form-top__label" for="yes" title="Порядок важен">Да</label>
        <input class="form-top__radio" type="radio" id="yes" name="answer" value="yes1" required
               title="Порядок важен">
        <label class="form-top__label" for="no" title="Порядок не важен">Нет</label>
        <input class="form-top__radio" type="radio" id="no" name="answer" value="no1" required
               title="Порядок не важен">
        <button class="form-bottom__button" type="submit">Ответить</button>
    </div>
    <hr>
</form>

MxlCalc/MxlCalc/Views/Combinations/form2.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top ">
        <h4 class="form-top__text">Все ли элементы множества А входят в КК?</h4>
        <label class="form-top__label" for="yes" title="Порядок важен">Да</label>
        <input class="form-top__radio" type="radio" id="yes" name="answer" value="yes2_2" required
               title="Порядок важен">
        <label class="form-top__label" for="no" title="Порядок не важен">Нет</label>
        <input class="form-top__radio" type="radio" id="no" name="answer" value="no2_2" required
               title="Порядок не важен">
        <button class="form-bottom__button" type="submit">Ответить</button>
    </div>
    <hr>
</form>

MxlCalc/MxlCalc/Views/Combinations/form2_1.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top">
        <h4 class="form-top__text">Есть ли в КК повторения элементов?</h4>
        <label class="form-top__label" for="yes" title="Порядок важен">Да</label>
        <input class="form-top__radio" type="radio" id="yes" name="answer" value="yes3" required
               title="Порядок важен">
        <label class="form-top__label" for="no" title="Порядок не важен">Нет</label>
        <input class="form-top__radio" type="radio" id="no" name="answer" value="no3" required
               title="Порядок не важен">
        <button class="form-bottom__button" type="submit">Ответить</button>
    </div>
    <hr />
</form>

MxlCalc/MxlCalc/Views/Combinations/form3.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top">
        <h4 class="form-top__text">Есть ли в КК повторения элементов?</h4>
        <label class="form-top__label" for="yes" title="Порядок важен">Да</label>
        <input class="form-top__radio" type="radio" id="yes" name="answer" value="yes2_3" required
               title="Порядок важен">
        <label class="form-top__label" for="no" title="Порядок не важен">Нет</label>
        <input class="form-top__radio" type="radio" id="no" name="answer" value="no2_3" required
               title="Порядок не важен">
        <button class="form-bottom__button" type="submit">Ответить</button>
    </div>
    <hr />
</form>

MxlCalc/MxlCalc/Views/Combinations/result.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top">
        <h4 class="main__calculator-text">Ваша конфигурация: @ViewBag.TypeOfConfigure</h4>
        <h4 class="main__calculator-text">Ответ: @ViewBag.Result</h4>
        <a  class="form-bottom__button" href="@Url.Action("Index","Combinations")">Назад</a>
    </div>
</form>

MxlCalc/MxlCalc/Views/Combinations/result1.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top">
        <h4 class="main__calculator-text">Введите n:</h4>
        <input class="body-input-text" type="text" name="n" required>
        <h4 class="main__calculator-text">Введите m:</h4>
        <input class="body-input-text" type="text" name="m" required>
        <button class="form-bottom__button btn" type="submit">Решить</button>
    </div>
</form>

MxlCalc/MxlCalc/Views/Combinations/result2.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top">
        <h4 class="main__calculator-text">Введите n:</h4>
        <input class="body-input-text" type="text" name="n" required>
        <button class="form-bottom__button btn" type="submit">Решить</button>
    </div>
</form> 

MxlCalc/MxlCalc/Views/Combinations/result3.cshtml
<form class="main__calculator-form" method="post">
    <div class="form-top">
        <h4 class="main__calculator-text">Введите m:</h4>
        <input class="body-input-text" type="text" name="m" required>
        <h4 class="main__calculator-text">Введите k через разделитель:</h4>
        <input class="body-input-text" type="text" name="k" required>
        <button class="form-bottom__button btn" type="submit">Решить</button>
    </div>
</form>

MxlCalc/MxlCalc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}

<section class="main__calculator">
    <h2 class="main__calculator-title">
        Калькуляторы
    </h2>
    <div class="main__calculator-body">
        <form class="main__calculator-form" method="get">
            <div class="form-top">
                <label class="form-top__tile">Выберите тему:</label>
                <select class="form-top__options" name="themes">
                    <option value="sets">Множества</option>
                    <option value="binary__relations" disabled alt="Пока недоступно">Бинарные отношения</option>
                    <option value="combinations">Комбинаторика</option>
                </select>
            </div>
            <div class="form-bottom">
                <button class="form-bottom__button" type="submit">Выбрать</button>
            </div>
            <p class="main__calculator-text">
                В меню выше можно выбрать раздел из дискретной математики, по которой вы хотите найти
                калькулятор.
            </p>
        </form>
    </div>

</section>
<hr>
<section class="main__information">
    <h2 class="main__information-title">
        Вы можете выбрать одну из следующих тем
    </h2>
    <p class="main__information-text main__information-text--1">
        <span class="bold">Множества</span> - есть 3 калькулятора:
        <ul class="main__information-text-list">
            <li class="main__information-text-item">Выполнить действие между двумя множествами</li>
            <li class="main__information-text-item">Решить уравнение с 2 и более множеств</li>
        </ul>
    </p>
    <p class="main__information-text main__information-text--2">
        <span class="bold">Бинарные отношения</span> - один калькулятор:<br />
        Проверить множество на различные свойства
    </p>
    <p class="main__information-text main__information-text--2">
        <span class="bold">Комбинаторика</span> - один калькулятор:<br />
        Выберите тип комбинаторной конфигурации для подсчёта.
    </p>

</section>

MxlCalc/MxlCalc/Views/Set/Equation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MxlCalc/MxlCalc/Views/Set/Index.cshtml
@{
    ViewData["Title"] = "Бинарные отношения";
}

<section class="main__calculator">
    <h2 class="main__calculator-title">
        Калькуляторы
    </h2>
    <div class="main__calculator-body">
        <form class="main__calculator-form" method="get">
            <div class="form-top">
                <p class="form-top__tile">
                    <label>Выберите задачу для решения:</label>
                </p>
                <select class="form-top__options" name="calculators">
                    <option value="operations">Операции над множествами</option>
                    <option value="equation" disabled>Решить уравнение</option>
                </select>
            </div>
            <div class="form-bottom">
                <button class="form-bottom__button" type="submit">Выбрать</button>
            </div>
            <p class="main__calculator-text">
                В меню выше можно выбрать раздел из дискретной математики, по которой вы хотите найти
                калькулятор.
            </p>
        </form>
    </div>

</section>
<hr>
<section class="main__information">
    <h2 class="main__information-title">
        Вы можете выбрать один из следующих калькуляторов:
    </h2>
    <p class="main__information-text">
        <span class="bold">Операции над множествами:</span><br />
        Вы можете выбрать два множества и выполнить между ними следующие операции:

        <ul class="main__information-text-list">
            <li class="main__information-text-item">Пересечение</li>
            <li class="main__information-text-item">Объединение</li>
            <li class="main__information-text-item">Разница</li>
            <li class="main__information-text-item">Симметричная разница</li>
        </ul>
    </p>
    <p class="main__information-text">
        <span class="bold">Решить уравнение:</span><br />
        Вы можете ввести уравнение используя операции над множествами.
    </p>
    
</section>

MxlCalc/MxlCalc/Views/Set/Operations.cshtml
@{
    ViewData["Title"] = "Операции над множествами";
    
}

<link href="@Url.Content("~/css/operations.min.css")" rel="stylesheet" type="text/css" />
<section class="main__calculator">
    <h2 class="main__calculator-title">
        Операции над множествами
    </h2>
    <div class="main__calculator-body">
        <form class="main__calculator-form" method="get">
            <div class="form-top">
                <h4 class="form-top__text">Выберите тип множества:</h4>
                <label class="form-top__label" for="digital" title="Множество состоит из цифр">Цифровой</label>
                <input class="form-top__radio" type="radio" id="digital" name="type" value="digital" required title="Множество состоит из цифр">
                <label class="form-top__label" for="alphabetic" title="Множество состоит из латинских букв">Буквенный</label>
                <input class="form-top__radio" type="radio" id="alphabetic" name="type" value="alphabetic" required title="Множество состоит из латинских букв">
                <hr>
                <p class="main__calculator-text">
                    Введите множества через разделитель
                </p>
                <div class="form-top__body">
                    <p class="body-input">
                        A = {
                        <input class="body-input-text" type="text" name="setA" required> }
                    </p>
                    <p class="body-select">
                        <select class="form-top__options" name="operation" id="" required>
                            <option value="intersect">&cap;</option>
                            <option value="union">&cup;</option>
                            <option value="setdiff">\</option>
                            <option value="setxor">&#916;</option>
                        </select><br />
                    </p>
                    <p class="body-input">
                        B = {
                        <input class="body-input-text" type="text" name="setB" required> }
                    </p>
                </div>
            </div>
            <div class="form-bottom">
                <button class="form-bottom__button" type="submit">Решить</button>
                <p class="form-bottom__answer">
                    Ответ: C = { @ViewBag.Result }
                </p>
            </div>

        </form>
    </div>

</section>

MxlCalc/MxlCalc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MxlCalc</title>
    <link rel="shortcut icon" href="@Url.Content("~/images/icon.ico")" type="image/x-icon">
    <link href="@Url.Content("~/css/style.min.css")" rel="stylesheet" type="text/css" />


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <div class="container">
                <div class="header__inner">
                    <a class="logo" href="@Url.Action("Index","Home")">
                        <img src="@Url.Content("~/images/logo.png")" alt="logo">
                    </a>
                    <nav class="menu">
                        <ul class="menu__list">
                            <li class="menu__list-item">
                                <a class="menu__list-link" href="@Url.Action("Index","Home")">Главная</a>
                            </li>
                            <li class="menu__list-item">
                                <a class="menu__list-link" href="#">О проекте</a>
                            </li>
                            <li class="menu__list-item">
                                <a class="menu__list-link" href="#">Обратная связь</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <main role="main" class="main">
            <div class="main__inner">
                <div class="container">
                    @RenderBody()
                </div>
            </div>
        </main>
        <footer class="footer">
            <div class="container">
                <div class="footer__inner">
                    <div class="footer__copyright">
                        <p>
                            &copy MxlCalc
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>